# **Image Classification**

In [1]:
!pip install opendatasets

In [2]:
import opendatasets as od
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
import cv2
from skimage.transform import resize
from skimage.io import imread
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [3]:
od.download("https://www.kaggle.com/datasets/chetankv/dogs-cats-images?resource=download&select=dataset")

Skipping, found downloaded files in "./dogs-cats-images" (use force=True to force download)


In [4]:
dir = 'dogs-cats-images/dataset/'
categories = ['dogs','cats']

test_dir = 'dogs-cats-images/dataset/test_set/'
train_dir = 'dogs-cats-images/dataset/training_set/'

data = []

for i in categories:
  path = os.path.join(train_dir, i)
  label = categories.index(i)

  for img in os.listdir(path):
    imgpath = os.path.join(path, img)
    pet_img = cv2.imread(imgpath, 0)
    pet_img = cv2.resize(pet_img, (50,50))
    image = np.array(pet_img).flatten()
    data.append([image, label])

print(len(data))

8000


In [5]:
(data[10])

[array([190, 194, 194, ...,  38, 103, 121], dtype=uint8), 0]

In [6]:
features = []
labels = []

for feature, label in data:
  features.append(feature)
  labels.append(label)

print(len(labels))
print(features[10])

8000
[190 194 194 ...  38 103 121]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size= 0.2, random_state= 77)

In [8]:
model = svm.SVC(C= 1, kernel= 'poly', gamma= 'auto')

In [9]:
model.fit(X_train, y_train)

SVC(C=1, gamma='auto', kernel='poly')

In [10]:
prediction = model.predict(X_test)

In [11]:
accuracy = model.score(X_test, y_test)
accuracy

0.571875

In [12]:
X_train_prediction = model.predict(X_train)
print(X_train_prediction)

[0 1 0 ... 0 0 1]


In [13]:
training_data_accuracy = accuracy_score(y_train, X_train_prediction)
print("Accuracy of training data: ",training_data_accuracy)

Accuracy of training data:  1.0


In [14]:
X_test_prediction = model.predict(X_test)
print(X_test_prediction)

[0 0 0 ... 1 1 1]


In [15]:
test_data_accuracy = accuracy_score(y_test, X_test_prediction)
print("Accuracy of testing data: ",test_data_accuracy)

Accuracy of testing data:  0.571875
